version: 2

jobs:
  test:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          - v2-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run: npm run lint

  deploy:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          - v2-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: npm run build

      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --only hosting

workflows:
  version: 2
  build_deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
      - deploy:
          filters:
            branches:
              only:
                - master
